### PR TITLE
update to 5.4.2

### PR DESCRIPTION
**Pull request by M-Waszkiewicz-Anaconda**

### CODE REVIEW

**Review by akabanovs — CHANGES_REQUESTED** [review]
I think packaging is required:
https://github.com/jupyter/qtconsole/blob/5.4.2/setup.py#L77

Worth addressing some linter errors (script flags and overspecification in the about section, url)

Also, pyzmq>=17.1 . Here, version need to be separated with a space.

**Comment by M-Waszkiewicz-Anaconda** [comment]
> I think packaging is required: https://github.com/jupyter/qtconsole/blob/5.4.2/setup.py#L77
> 
> Worth addressing some linter errors (script flags and overspecification in the about section, url)
> 
> Also, pyzmq>=17.1 . Here, version need to be separated with a space.

done

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by akabanovs — APPROVED** [review]
LGTM

**Pull request merged**
